# Generated by Django 3.2.20 on 2023-08-14 15:26

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangocms_translations', '0010_translationquote_delivery_date_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='provider_backend',
            field=models.CharField(choices=[('SupertextTranslationProvider', 'Supertext'), ('GptTranslationProvider', 'GPT')], max_length=100),
        ),
        migrations.CreateModel(
            name='AppTranslationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('pending_quote', 'Pending quote from provider'), ('pending_approval', 'Pending approval of quote'), ('ready_for_submission', 'Pending submission to translation provider'), ('in_translation', 'In translation'), ('import_started', 'Import started'), ('import_failed', 'Import failed'), ('imported', 'Imported'), ('cancelled', 'Cancelled')], default='draft', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('date_imported', models.DateTimeField(blank=True, null=True)),
                ('source_language', models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=10)),
                ('target_language', models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=10)),
                ('provider_backend', models.CharField(choices=[('SupertextTranslationProvider', 'Supertext'), ('GptTranslationProvider', 'GPT')], max_length=100)),
                ('provider_order_name', models.CharField(blank=True, max_length=255)),
                ('provider_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('export_content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('request_content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('selected_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangocms_translations.translationquote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
