# Generated by Django 3.2.20 on 2023-08-14 15:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0011_auto_20230814_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apptranslationrequest',
            options={'verbose_name': 'App Translation request', 'verbose_name_plural': 'App Translation requests'},
        ),
        migrations.CreateModel(
            name='AppTranslationQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField()),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date_name', models.CharField(blank=True, max_length=10, null=True)),
                ('price_currency', models.CharField(max_length=10)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='djangocms_translations.apptranslationrequest')),
            ],
        ),
    ]
