# Generated by Django 3.2.20 on 2023-08-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0012_auto_20230814_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTranslationRequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='djangocms_translations.apptranslationrequest')),
            ],
        ),
    ]
