# Generated by Django 3.2.20 on 2023-08-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0013_apptranslationrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptranslationrequestitem',
            name='link_model',
            field=models.CharField(default='people', max_length=100, verbose_name='Link model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apptranslationrequestitem',
            name='link_object_id',
            field=models.PositiveIntegerField(default=19, verbose_name='Link object id'),
            preserve_default=False,
        ),
    ]
