# Generated by Django 3.2.20 on 2023-08-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0015_apptranslationrequestitem_app_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='selected_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangocms_translations.apptranslationquote'),
        ),
    ]
