# Generated by Django 3.2.20 on 2023-08-15 11:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0016_alter_apptranslationrequest_selected_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTranslationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_translated', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('pending_quote', 'Pending'), ('failed', 'Failed/cancelled'), ('done', 'Done')], default='open', max_length=100)),
                ('request_content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('response_content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('provider_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='djangocms_translations.apptranslationrequest')),
            ],
        ),
    ]
