# Generated by Django 3.2.20 on 2023-08-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0017_apptranslationorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTranslationImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('state', models.CharField(choices=[('started', 'Import started'), ('failed', 'Import failed'), ('imported', 'Imported')], default='started', max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='djangocms_translations.apptranslationrequest')),
            ],
        ),
    ]
