# Generated by Django 3.2.20 on 2023-08-16 11:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0018_apptranslationimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptranslationrequest',
            name='export_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apptranslationrequest',
            name='request_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
