# Generated by Django 3.2.21 on 2023-10-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0020_auto_20230912_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='source_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=10),
        ),
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='target_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=10),
        ),
        migrations.CreateModel(
            name='TranslationDirective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', max_length=10, verbose_name='language')),
                ('directive_item', models.TextField(blank=True, null=True, verbose_name='directive item')),
                ('translation_of', models.ForeignKey(blank=True, limit_choices_to={'language_code': 'de'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djangocms_translations.translationdirective', verbose_name='translation of')),
            ],
            options={
                'verbose_name': 'translation directive',
            },
        ),
    ]
