# Generated by Django 3.2.21 on 2023-10-02 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0021_auto_20231002_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationdirective',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translationdirective',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
