# Generated by Django 3.2.21 on 2023-10-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0023_remove_translationdirective_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationdirective',
            name='directive_item',
        ),
        migrations.RemoveField(
            model_name='translationdirective',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='translationdirective',
            name='translation_of',
        ),
        migrations.AddField(
            model_name='translationdirective',
            name='master_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', max_length=10, verbose_name='master language'),
        ),
        migrations.CreateModel(
            name='TranslationDirectiveInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', editable=False, max_length=10, verbose_name='language')),
                ('directive_item', models.TextField(blank=True, null=True, verbose_name='directive item')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='djangocms_translations.translationdirective')),
            ],
        ),
    ]
