# Generated by Django 3.2.21 on 2023-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0024_auto_20231002_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationdirectiveinline',
            name='title',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
