# Generated by Django 3.2.21 on 2023-10-03 10:09

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0025_translationdirectiveinline_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationdirectiveinline',
            options={'ordering': ['master__master_language']},
        ),
        migrations.AlterField(
            model_name='translationdirectiveinline',
            name='directive_item',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='directive item'),
        ),
    ]
