# Generated by Django 3.2.23 on 2024-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0037_auto_20240315_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='translate_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='translate_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='source_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('it', 'Italian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='target_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('it', 'Italian')], max_length=10),
        ),
    ]
