# Generated by Django 3.2.23 on 2024-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0038_auto_20240318_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='export_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
