# Generated by Django 3.2.23 on 2024-03-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0039_translationrequest_export_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='translate_seo',
            field=models.BooleanField(default=True),
        ),
    ]
