# Generated by Django 4.2.11 on 2024-12-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0040_translationrequest_translate_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='provider_backend',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='source_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French')], max_length=10),
        ),
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='target_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French')], max_length=10),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='provider_backend',
            field=models.CharField(choices=[('DeeplProvider', 'DeepL')], max_length=100),
        ),
        migrations.CreateModel(
            name='TranslationGlossarInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(editable=False, max_length=10, verbose_name='language')),
                ('title', models.CharField(editable=False, max_length=255, null=True)),
                ('creation_time', models.DateTimeField()),
                ('glossar_csv', models.FileField(blank=True, null=True, upload_to='glossar/')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations_glossar', to='djangocms_translations.translationdirective')),
            ],
            options={
                'ordering': ['master__master_language'],
            },
        ),
    ]
