# Generated by Django 4.2.11 on 2024-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0041_alter_apptranslationrequest_provider_backend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationglossarinline',
            name='creation_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
