# Generated by Django 4.2.11 on 2024-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0042_alter_translationglossarinline_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationglossarinline',
            name='glossary_id',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='translationglossarinline',
            name='language',
            field=models.CharField(max_length=10, verbose_name='target language'),
        ),
    ]
