# Generated by Django 4.2.11 on 2024-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0043_translationglossarinline_glossary_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptranslationimport',
            name='state',
            field=models.CharField(choices=[('started', 'Import started'), ('failed', 'Import failed'), ('imported', 'Done')], default='started', max_length=100),
        ),
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('pending_quote', 'Pending quote from provider'), ('pending_approval', 'Pending approval of quote'), ('ready_for_submission', 'Pending submission to translation provider'), ('in_translation', 'In translation'), ('import_started', 'Import started'), ('import_failed', 'Import failed'), ('imported', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='translationimport',
            name='state',
            field=models.CharField(choices=[('started', 'Import started'), ('failed', 'Import failed'), ('imported', 'Done')], default='started', max_length=100),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('pending_quote', 'Pending quote from provider'), ('pending_approval', 'Pending approval of quote'), ('ready_for_submission', 'Pending submission to translation provider'), ('in_translation', 'In translation'), ('import_started', 'Import started'), ('import_failed', 'Import failed'), ('imported', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=100),
        ),
    ]
