# Generated by Django 4.2.11 on 2024-12-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0044_alter_apptranslationimport_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationglossarinline',
            name='entries',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
