# Generated by Django 4.2.26 on 2026-03-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0045_translationglossarinline_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='provider_backend',
            field=models.CharField(choices=[('DeeplProvider', 'DeepL'), ('TranslinguaProvider', 'Translingua')], max_length=100),
        ),
    ]
