# Generated by Django 4.2.11 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0045_translationglossarinline_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationdirectiveinline',
            name='prompt_instruction',
            field=models.TextField(blank=True, default='', help_text='Optional instruction appended to the translation prompt for this language (e.g. punctuation rules).', verbose_name='prompt instruction'),
        ),
    ]
