# Generated by Django 4.2.11 on 2026-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0045_translationglossarinline_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='source_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=10),
        ),
        migrations.AlterField(
            model_name='apptranslationrequest',
            name='target_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=10),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='provider_backend',
            field=models.CharField(choices=[('GptTranslationProvider', 'GPT')], max_length=100),
        ),
    ]
