# Generated by Django 5.2.12 on 2026-05-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_translations', '0046_alter_apptranslationrequest_source_language_and_more'),
        ('djangocms_translations', '0046_translationdirectiveinline_prompt_instruction'),
    ]

    operations = [
    ]
