# Generated by Django 5.2.12 on 2026-07-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('djangocms_translations', '0048_alter_dynamic_choice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedplaceholder',
            name='placeholder',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_placeholders', to='cms.placeholder'),
        ),
    ]
